routes/web.php
<?php

use App\Http\Controllers\LeaguesController;
use App\Http\Controllers\TeamsController;
use App\Models\Leagues;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('leagues.index'));
});

Route::resources([
    'teams' => TeamsController::class,
    'leagues' => LeaguesController::class,
]);

Route::put('/teams/status/{team}', [TeamsController::class, 'updateStatus'])->name('teams.status');

Route::get('/leagues/start/{id}', [LeaguesController::class, 'startLeague'])->name('leagues.start');
Route::get('/leagues/playweek/{id}', [LeaguesController::class, 'playWeek'])->name('leagues.playweek');
Route::get('/leagues/playallweeks/{id}', [LeaguesController::class, 'playAllWeeks'])->name('leagues.playAllWeeks');

resources/views/layout/footer.blade.php
    </div>
    <footer>

    </footer>
    </body>
</html>

resources/views/layout/header.blade.php
<html>
    <head>
        <title>PremierLeague</title>
        <meta name="csrf-token" content="{{ csrf_token() }}" />
        <link rel="stylesheet" href="{{ asset('css/bootstrap/bootstrap.min.css') }}" />
        <link rel="stylesheet" href="{{ asset('css/fonts/font-awesome.min.css') }}" />
        <link rel="stylesheet" href="{{ asset('css/style.css') }}" />
        <script type="text/javascript" src="{{ asset('js/jquery.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('js/bootstrap/bootstrap.min.js') }}"></script>
        <script>
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
        </script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Teams
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{route('teams.index')}}">All Teams</a>
                            <a class="dropdown-item" href="{{route('teams.create')}}">Add Team</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Leagues
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{route('leagues.index')}}">All Leagues</a>
                            <a class="dropdown-item" href="{{route('leagues.create')}}">Add League</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container-fluid">
            <br>